export {
  blastTargets,
  boardCells,
  boardPlates,
  boardWalls,
  collapseWalls,
  createBoard,
  criticalCells,
  criticalExplosions,
  deepBlastTargets,
  deepDegree,
  detonate,
  diagNeighborIds,
  eaterAt,
  getCell,
  hashBoard,
  isArmoredPlate,
  isCrackedPlate,
  isCritical,
  isEaterCell,
  isHousingPlate,
  isNearCritical,
  legalMoves,
  mapBounds,
  nearCriticalCount,
  occupiedCount,
  orthoNeighborIds,
  revealEaters,
  seedBoard,
  threshold,
  tokenCount,
} from './board';
export { stepCascade } from './cascade';
export { activateEater, nextMeal, runEaterPhase } from './eater';
export { createGame, applyTurn } from './game';
export { cellId, opponentOf, parseCellId } from './ids';
export { applyMove } from './move';
export type { CascadeStep } from './cascade';
export type {
  Board,
  CellId,
  CellState,
  EaterState,
  EaterStep,
  Game,
  HasPlaced,
  IllegalMoveReason,
  MapCell,
  MapDefinition,
  MoveFailure,
  MoveResult,
  MoveSuccess,
  Outcome,
  Owner,
  PlayerId,
  TokenSeed,
  TokenTransfer,
  TurnResult,
  TurnSuccess,
  WaveStep,
  WinCause,
} from './types';
export type { Explosion, WallDamage } from './board';
